settings:
    global_theme: freelancer
    title: "Freelancer"
    active_sections:
        - portfolio
        - about
        - contact
#    should be used to define what kind of website
    type: singlepage
    mail: "test@test.com"
    header: true
    footer: true
    available_lang: [en,fr]
header:
    type: freelancer_header
    data:
        punch_phrase_1: "text"
        punch_phrase_2: "text"
        tell_me_more: "text"
sections:
    about:
        type: freelancer_about
        data:
            heading: "text"
            subheading: "text"
            timeline:
                launch:
                    date: "text"
                    name: "text"
                    presentation: "text"
                    image: "image"
                agency_born:
                    date: "text"
                    name: "text"
                    presentation: "text"
                    image: "image"
                full_service:
                    date: "text"
                    name: "text"
                    presentation: "text"
                    image: "image"
            phase_2:
                    date: "text"
                    name: "text"
                    presentation: "text"
                    image: "image"
            end_about:
                name: "text"

    portfolio:
        type: freelancer_portfolio
        data:
            heading: "text"
            subheading: "text"
            service_list:
                ecommerce:
                    name: "text"
                    presentation: "text"
                    icon: "lightbulb-o"
                responsive:
                    name: "text"
                    presentation: "text"
                    icon: "laptop"
                web_security:
                    name: "text"
                    presentation: "text"
                    icon: "lock"
    contact:
        type: freelancer_contact
        data:
            heading:
            subheading:
footer:
    type: freelancer_footer
    data:
        copyright: "text"
        syndication:
            facebook: "https://www.facebook.com/"
            twitter:
            linkedin: "https://www.linkedin.com/"
        links:
            privacy:
                name: "text"
                url: "https://www.linkedin.com/"
            terms:
                name: "text"
                url: "https://www.linkedin.com/"